project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - about.qmd
  - pages/california_final_page.qmd
  - pages/adamguggenheimfinalEIAUS.qmd
  - pages/texas_website_final.qmd
  #pages/SP_page_VA.qmd

  #post-render: Rscript cleanup/clean_docs_dir.R

  preview:
    port: 167
    browser: true
    navigate: true

website:
  title: "Electricity Trends Across the U.S. and States"
  description: "A data-driven exploration of electricity trends across the United States, California, Texas, and Virginia."

  navbar:
    left:
      - text: "United States"
        href: pages/adamguggenheimfinalEIAUS.qmd

      - text: "California"
        href: pages/california_final_page.qmd

      - text: "Texas"
        href: pages/texas_website_final.qmd

      #text: "Virginia"
        #href: pages/SP_page_VA.qmd

    right:
      - text: "Home"
        href: index.qmd

      - text: "About"
        href: about.qmd

      - icon: github
        href: "https://github.com/slicesofdata/eia-167-2025"
        aria-label: GitHub

page-footer:
  left: |
    made with [Quarto](https://quarto.org)
  center: |
    [Contact me](mailto:myemail@mydomain.com)
  right: |
    [GitHub Repo](https://github.com/slicesofdata/eia-167-2025)
  background: "black"


format:
  html:
    theme:
      light: [cosmo, styles/example-light.scss]
      dark: [cosmo, styles/example-dark.scss]
    toc: true
    toc-depth: 3
    toc-expand: true
    fig-align: center
    include-in-header: "fonts/fontawesome.html"
